### ISSUE TITLE
Able to click register without required fields

### ISSUE THREAD

**Issue by hunterwilkins2** [galaxyproduction/bulldog-books#25]
I see where you added the required fields with yup but I am still able to click register without filling them out. Should probably add a check to make sure all the required fields are filled out before the user can continue.

**Comment by GaryBarnes13** [comment]
Yea I noticed that. I thought Formik was supposed to prevent submission in the presense of errors, but it looks like I may need to add this manually (see https://formik.org/docs/guides/form-submission) . Will look into this later tonight

**Comment by GaryBarnes13** [comment]
Looks like this feature is working for the login page (values are only logged to console when no errors are present), so I likely just missed a few lines of code somewhere. Should be a quick fix

**Comment by GaryBarnes13** [comment]
Fixed this. Still not sure why this seems to be working for the login page automatically, and I didn't fix it in the most elegant way, but the form will not be able to submit if there are any errors, and if any of the 4 mandatory fields are untouched
