### ISSUE TITLE
Bootstrap not found

### ISSUE THREAD

**Issue by galaxyproduction** [galaxyproduction/bulldog-books#4]
I think Gary needs to push bootstrap.min.css or add a local version into the repository.

**Comment by GaryBarnes13** [comment]
Not exactly sure why this is happening. Let me search around for a minute. That stylesheet isn't something I put in .gitignore, it is just an import that is required after installing Bootstrap [see here](https://react-bootstrap.github.io/getting-started/introduction). May be an issue with the way I ran npm install...

**Comment by GaryBarnes13** [comment]
Based on [this article](https://www.pluralsight.com/guides/how-to-use-react-bootstrap-with-npm), it seems that all I need to do is run the install command and import that stylesheet, which I have done already
