### ISSUE TITLE
Manage Promotions

### ISSUE THREAD

**Issue by hunterwilkins2** [galaxyproduction/bulldog-books#40]
# Requirments
- Only admins can manage promotions
- Promotions should automatically be emailed to users with the option to receive promotions
- Admins cannot delete or update a promotions once it has been created

**Comment by nssafir** [comment]
Any ideas why i'd be getting this error when i put a button inside a formik (@GaryBarnes13 )
![image](https://user-images.githubusercontent.com/47368416/113795288-828aa400-971a-11eb-83e7-5072bf1d988d.png)

**Comment by GaryBarnes13** [comment]
Can you attach your code, or let me know what file it is in? I have not received this error before, but it sounds like you might just be missing some syntax formik is expecting. For some simple examples of Formik, see the login page and [here](https://formik.org/docs/guides/validation). From what I can tell by googling this, it really doesn't look like a formik issue, but rather, a general React issue.

**Comment by nssafir** [comment]
@GaryBarnes13  I pushed the code in the managePromotions branch. It's in the `ManagePromotions.js` file.

**Comment by GaryBarnes13** [comment]
Looks like you're missing quite a bit of syntax that Formik is expecting, specifically under the <Form.Control> tag. Look at some of the other examples of the forms I built to see this, the best one to check would probably be the registration form. Also, you shouldn't have to disable no-unused-vars for those lines, since all of those values are needed to build a form. See [here](https://www.youtube.com/watch?v=FD50LPJ6bjE) for an overview on forms with Formik if my examples aren't sufficient

**Comment by nssafir** [comment]
> Looks like you're missing quite a bit of syntax that Formik is expecting, specifically under the <Form.Control> tag. Look at some of the other examples of the forms I built to see this, the best one to check would probably be the registration form. Also, you shouldn't have to disable no-unused-vars for those lines, since all of those values are needed to build a form. See [here](https://www.youtube.com/watch?v=FD50LPJ6bjE) for an overview on forms with Formik if my examples aren't sufficient

Thanks Gary, I was able to get it resolved

**Comment by nssafir** [comment]
@galaxyproduction could you look at the  `server.js` code on the managePromotions branch? I am gettign the following error after adding the two lines about the promotions route. 

![image](https://user-images.githubusercontent.com/47368416/114076816-196b7380-9875-11eb-8a91-edbbb094003e.png)

**Comment by hunterwilkins2** [comment]
Its routes with an 's'.... lol
