### ISSUE TITLE
Figure out what a promotion is

### ISSUE THREAD

**Issue by hunterwilkins2** [galaxyproduction/bulldog-books#41]
# What the hell is a promotion?
- Is it a sale on a particular book?
- Is it a general 20% off all purchases?
- What is the time span a promotion is active?

# What we need to do
- [ ] Update the promotions schema
- [ ] Add the routes in issue #40

**Comment by nssafir** [comment]
1. Do promotions correspond to specific books?
2. Should a promotion have a specified end date (and then be active from it's creation to it's end date)

**Comment by nssafir** [comment]
https://piazza.com/class/kjnjczjdlmr38b

**Comment by hunterwilkins2** [comment]
I think the way we should set it up is that the promotion is a flat discount on all books in the order. And then the promotion has a specific end date and optional start date or the date of creation. We can wait and see what she says on piazza or just go ahead and implement it and change anything if need be. They seem pretty lenient on stuff not explicitly stated in the rubric.

**Comment by nssafir** [comment]
I talked with someone else and I think you're right. I'm going to go ahead and implement it that way, can always change it later
