### ISSUE TITLE
Admins can manage users

### ISSUE THREAD

**Issue by hunterwilkins2** [galaxyproduction/bulldog-books#43]
# Requirments
- [ ] Admins can suspend and unsuspend users
- [ ] User should not have login/access to features if they are suspended
- [ ] Automatically email when a user is suspended or unsuspended

**Comment by KA2010** [comment]
Is user type here suppose to be employee or just user I am little confused what kind of user admin can suspend?

**Comment by KA2010** [comment]
nvm i think user type should be customer

**Comment by hunterwilkins2** [comment]
I think an admin can suspend both customers and employees. You will just have to add a check that a user is not an admin and suspend all other users

**Comment by hunterwilkins2** [comment]
Nmv, actually I just read the piazza post about this. Admins can only suspend customers. https://piazza.com/class/kjnjczjdlmr38b?cid=98

**Comment by KA2010** [comment]
Yes, I have read this post, but still this is confusing part
