### ISSUE TITLE
Admin cookies not recognized when redirected to the addbook page

### ISSUE THREAD

**Issue by sking115422** [galaxyproduction/bulldog-books#64]
I noticed last night that when I move from the homepage as admin to the add books page the navbar does not render the manage users or manage promotion buttons so i think there may be an issue with cookies when the page transfer. I tried looking in to it last night and couldnt figure out what was wrong. The weird thing is the add books page still will allow a new book to be post to the database. Let me know if any of you guys can resolve the issue.

**Comment by GaryBarnes13** [comment]
Seems to be working for me

**Comment by GaryBarnes13** [comment]
Will leave open so others can test it as well

**Comment by sking115422** [comment]
cool ill restart my machine later and rerun everything and see if it fixes it
