### ISSUE TITLE
Incorrect user type when unsuspending inactive users

### ISSUE THREAD

**Issue by sking115422** [galaxyproduction/bulldog-books#67]
I was testing the manage user page today, and i found a bug that if you suspend then unsuspend an inactive user it sets their status to active in stead of back to inactive. This should probably be fixed because this could leave to users with active status with out confirming their email.

**Comment by sking115422** [comment]
![image](https://user-images.githubusercontent.com/63437172/114777846-25a67380-9d42-11eb-8186-2911ac85e4b4.png)

I think we need a conditional statement here to change based on cookie or something

**Comment by hunterwilkins2** [comment]
Ummm..... I don't know a good solution to fix this. I don't really want to add another db field to store the previous status of the user. I guess we can change it to make the user's account inactive if they are unsuspended and they will have to reconfirm their email. It's not a great solution but it works. What do you think?
